### ISSUE TITLE
could you please make a output console in bottom pane ? when paneItemPosition is set to 'bottom'

### ISSUE THREAD

**Issue by skywind3000** [ksxatompackages/cmd-exec-documentation#1]
Compiler error message and source code can be viewed at the same time, if output console can be placed in the bottom area just like UltraEdit or EditPlus. otherwise I need to switch between source code and error message frequencely.

**Comment by KSXGitHub** [comment]
Thanks for your feedback. I have to improve the document.

Solution: Use `"up"`, `"down"` instead of `"top"`, `"bottom"`.
