### ISSUE TITLE
How to open an instance of this package

### ISSUE THREAD

**Issue by doug-wood** [ksxatompackages/cmd-exec-documentation#3]
How do you open an instance of a command prompt. Do i need to set this up manually or is there a default ?

Thanks

**Comment by doug-wood** [comment]
figured it out

**Comment by KSXGitHub** [comment]
Congratulation!
And also, I do not understand why people open issue here, but [ksxatompackages/cmd-exec](https://github.com/ksxatompackages/cmd-exec) is more appreciated
